name: CI Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'fastetl/**'
      - 'tests/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'fastetl/**'
      - 'tests/**'

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout FastETL
      uses: actions/checkout@v3
      with:
        path: FastETL

    - name: Setup environment
      working-directory: ./FastETL
      env:
        TAG_NAME: dev-build
      run: make setup

    - name: Run Tests
      working-directory: ./FastETL
      run: make tests
