name: CI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout FastETL
      uses: actions/checkout@v3
      with:
        path: FastETL

    - name: Setup environment
      working-directory: ./FastETL
      run: make setup

    - name: Run Tests
      working-directory: ./FastETL
      run: make tests
