name: Trigger Workflow in airflow2-docker Repository
on:
  workflow_run:
    workflows:
      - "Build and Publish"
    types:
      - completed

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.AIRFLOW2_DOCKER_TOKEN }}
          repository: economiagovbr/airflow2-docker
          event-type: update-dependencies
